os:
- linux
dist: xenial
language: nix
sudo: required

before_script:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- sudo mkdir -p /etc/nix
- echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
- sudo launchctl kickstart -k system/org.nixos.nix-daemon || true

services:
- docker

jobs:
  include:
    name: "Build"
    script:
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - cachix use studio
    - nix-build -j2 -A studio-env . | (if test -n "$CACHIX_SIGNING_KEY"; then cachix push studio; else cat; fi)
    name: "Docker"
    - docker build -t studioproject/$TRAVIS_BRANCH .
    - docker run -t studioproject/$TRAVIS_BRANCH test
    - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push studioproject/$TRAVIS_BRANCH; fi
